<?php
global $nico_theme_name, $nico_theme, $nico_theme_positions;
$nico_theme_name = '<div style="color:#777;float:right;padding:2px;border:2px solid #999;font-weight:600;font-size:11px;margin-left:5px;">BOXED</div>';
$nico_theme = 'boxed';
$nico_theme_positions = 
array(
	'menu' => 'Menu',
	'top' => 'Page top',
	'top_links' => 'Top links',
	'header' => 'Header',
	'footer_top' => 'Footer top',
	'content_top' => 'Content top',
	'content_bottom' => 'Content bottom',
	'column_left' => 'Column left',
	'column_right' => 'Column right',
	'product_tabs' => 'Product tabs (product page)'
);


$ocmods_ignore = array('nico_image_cropresize.ocmod.xml', 'nico_image_resizewidth.ocmod.xml', 'nico_image_cropresize_product.ocmod.xml', 'nico_image_resizewidth.ocmod.xml', 'nico_image_resizewidth_category.ocmod.xml');
